### ISSUE TITLE
is there a dll for linux

### ISSUE THREAD

**Issue by sherifomran** [youssefsharief/arabic-tacotron-tts#2]
alsalam alikum 
i would like to run it on an embedded device such as raspberry pi and thus i need a dll or a simple lite way to run it or devices with limited resources. It is possible to integrate it into festival or into the libraries supported by the Speech Dispatcher. please give me a feed back

thank you in advance
regards,
Dr. Sherif Omran

**Comment by yoosif0** [comment]
W Alaykom El Salam,

You are welcome.
Sadly, I do not think any of this is possible.

**Comment by sherifomran** [comment]
Can you please investigate?how can i contact you directly, what is your email. Do you have linkedin !

    On Wednesday, March 20, 2019, 10:14:07 AM GMT+1, Youssef Sherif <notifications@github.com> wrote:  
 
 
W Alaykom El Salam,

You are welcome.
Sadly, I do not think any of this is possible.

**Comment by yoosif0** [comment]
me attt yoosif.com
