### ISSUE TITLE
Demo without server

### ISSUE THREAD

**Issue by m0ckingbird23** [youssefsharief/arabic-tacotron-tts#5]
Hey,

i was wondering how can i demo the model without a server , for example the input is a txt file where i have put all text sentences i would like to be synthesized then i get set of wav files for each sentence

**Comment by ghost** [comment]
@youssefsharief

**Comment by yoosif0** [comment]
You can do this. You can check what does the `synthesize.py` file calls and modify the code to save the wav files to a specific folder for example.
