### ISSUE TITLE
Time lag for execution on tensorflow cpu

### ISSUE THREAD

**Issue by nafezq** [youssefsharief/arabic-tacotron-tts#7]
This is more of a question rather than an issue, I installed arabic-tacotron on 2 machines, one with a i5 cpu and 4G Rams, the other i7 with 8G rams. On those machines it took arabic-tacotron 125 seconds (i5) and 95 seconds (i7) to produce the sound.
The english tacotron of Kiethito produces sound after 35 seconds on the i7 machine.
Wonder if you can share how much time arabic-tacotron takes to produce sound on machines that you installed it on, and what might be causing the big slow down compared to Kiethito's tacotron.
Also are there any plans to port it to tensor 2?

**Comment by yoosif0** [comment]
There are no plans to change. Having a good GPU and using it to synthesize the sound instead of the CPU would improve performance. I do not remember how much time did it take. Sorry for the late reply.
